version: '3.9'
services:

  mariadb:
    container_name: manychat.mariadb
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'default'
      TZ: Europe/Moscow
    ports:
     - "3306:3306"
   
  nginx:
    container_name: manychat.nginx
    build:
      context: .
    environment:
      TZ: Europe/Moscow
    ports:
      - "8080:8080"
    volumes:
      - ./:/var/www:delegated
